### ISSUE TITLE
Setup failed with Home Assistant Core 2025.3

### ISSUE THREAD

**Issue by Dieghito72** [h4de5/home-assistant-toshiba_ac#220]
Setup failed for custom integration 'toshiba_ac': Requirements for toshiba_ac not found: ['toshiba-ac==0.3.10'].

Rolled back HA to 2025.2.5

**Comment by Kahera** [comment]
Following errors in the log: 
```
Unable to install package toshiba-ac==0.3.10: × No solution found when resolving dependencies: ╰─▶ Because azure-iot-device>=2.9.0,<=2.10.0 depends on paho-mqtt>=1.4.0,<2.0.0 and paho-mqtt==2.1.0, we can conclude that azure-iot-device>=2.9.0,<=2.10.0 cannot be used. And because only the following versions of azure-iot-device are available: azure-iot-device<=2.9.0 azure-iot-device==2.10.0 azure-iot-device==2.11.0 azure-iot-device==2.12.0 azure-iot-device==2.13.0 azure-iot-device==2.13.1 azure-iot-device==2.14.0 we can conclude that azure-iot-device>=2.9.0,<2.11.0 cannot be used. (1) Because azure-iot-device==2.11.0 depends on paho-mqtt>=1.4.0,<2.0.0 and paho-mqtt==2.1.0, we can conclude that azure-iot-device==2.11.0 cannot be used. And because we know from (1) that azure-iot-device>=2.9.0,<2.11.0 cannot be used, we can conclude that azure-iot-device>=2.9.0,<2.12.0 cannot be used. (2) Because azure-iot-device>=2.12.0 depends on paho-mqtt>=1.6.1,<2.0.0 and paho-mqtt==2.1.0, we can conclude that azure-iot-device>=2.12.0 cannot be used. And because we know from (2) that azure-iot-device>=2.9.0,<2.12.0 cannot be used, we can conclude that azure-iot-device>=2.9.0 cannot be used. And because toshiba-ac==0.3.10 depends on azure-iot-device>=2.9.0 and you require toshiba-ac==0.3.10, we can conclude that your requirements are unsatisfiable. hint: Pre-releases are available for `azure-iot-device` in the requested range (e.g., 3.0.0b2), but pre-releases weren't enabled (try: `--prerelease=allow`)
```

and 
`Setup failed for custom integration 'toshiba_ac': Requirements for toshiba_ac not found: ['toshiba-ac==0.3.10'].`

**Comment by Benoit34590** [comment]
Same error with 2025.3

**Comment by Haaksimo** [comment]
Works with 2025.2.5 but not 2025.3

**Comment by danmiles86** [comment]
Same :(

**Comment by DE8** [comment]
same problem

**Comment by is200043** [comment]
Setup failed for custom integration 'toshiba_ac': Requirements for toshiba_ac not found: ['toshiba-ac==0.3.10'].

**Comment by mesicekvlada** [comment]
same problem

**Comment by wolfofnorway** [comment]
Same problem

**Comment by maarten117** [comment]
Same here.

**Comment by Stratovarius666** [comment]
Same here.

**Comment by Marlboro35** [comment]
Same with 2025.3

**Comment by NDBassie** [comment]
same issue here. Dependency cannot be resolved with 2025.3

**Comment by albaintor** [comment]
Hi, I made a temporary fix :
https://github.com/h4de5/home-assistant-toshiba_ac/pull/221

This is not clean at all but it is working. You can just copy the content of my fork into your custom_component folder and restart HA

**Comment by Kahera** [comment]
You're an absolute gem, @albaintor!

**Comment by SA7BNT** [comment]
> Hi, I made a temporary fix : [#221](https://github.com/h4de5/home-assistant-toshiba_ac/pull/221)
> 
> This is not clean at all but it is working. You can just copy the content of my fork into your custom_component folder and restart HA

Can confirm that it works again for me too. Thanks @albaintor

**Comment by blbeczech82** [comment]
> Hi, I made a temporary fix : [#221](https://github.com/h4de5/home-assistant-toshiba_ac/pull/221)
> 
> This is not clean at all but it is working. You can just copy the content of my fork into your custom_component folder and restart HA

It broke again after 2025.3.1 update.
Here's the new link for .3.1 from @albaintor patch:

[https://github.com/h4de5/home-assistant-toshiba_ac/archive/0fc22ed3edacd8cd1cc336cd0d566f6a3adff440.zip](url)

**Comment by sh4rks** [comment]
Hi @h4de5 ,

Could you accept the merge request for the workaround developed by @albaintor ?

It will be useful until a fix in azure 

Thanks

**Comment by h4de5** [comment]
> Hi [@h4de5](https://github.com/h4de5) ,
> 
> Could you please accept the merge request for the workaround developed by [@albaintor](https://github.com/albaintor) ?
> 
> It will be useful until a fix in azure
> 
> Thanks

this would copy the whole api into this repository. please understand thats not a
the way to go from the perspective of the integration. you can use the branch or the provided zip file both should work.

**Comment by smoketabs** [comment]
Same here. "The following integrations and platforms could not be set up: toshiba_ac"

Logger: homeassistant.setup
Source: setup.py:275
First occurred: 10:29:26 (1 occurrences)
Last logged: 10:29:26

Setup failed for custom integration 'toshiba_ac': Requirements for toshiba_ac not found: ['toshiba-ac==0.3.10'].

Logger: homeassistant.util.package
Source: util/package.py:159
First occurred: 10:29:21 (3 occurrences)
Last logged: 10:29:26

Unable to install package toshiba-ac==0.3.10: × No solution found when resolving dependencies: ╰─▶ Because azure-iot-device>=2.9.0,<=2.10.0 depends on paho-mqtt>=1.4.0,<2.0.0 and paho-mqtt==2.1.0, we can conclude that azure-iot-device>=2.9.0,<=2.10.0 cannot be used. And because only the following versions of azure-iot-device are available: azure-iot-device<=2.9.0 azure-iot-device==2.10.0 azure-iot-device==2.11.0 azure-iot-device==2.12.0 azure-iot-device==2.13.0 azure-iot-device==2.13.1 azure-iot-device==2.14.0 we can conclude that azure-iot-device>=2.9.0,<2.11.0 cannot be used. (1) Because azure-iot-device==2.11.0 depends on paho-mqtt>=1.4.0,<2.0.0 and paho-mqtt==2.1.0, we can conclude that azure-iot-device==2.11.0 cannot be used. And because we know from (1) that azure-iot-device>=2.9.0,<2.11.0 cannot be used, we can conclude that azure-iot-device>=2.9.0,<2.12.0 cannot be used. (2) Because azure-iot-device>=2.12.0 depends on paho-mqtt>=1.6.1,<2.0.0 and paho-mqtt==2.1.0, we can conclude that azure-iot-device>=2.12.0 cannot be used. And because we know from (2) that azure-iot-device>=2.9.0,<2.12.0 cannot be used, we can conclude that azure-iot-device>=2.9.0 cannot be used. And because toshiba-ac==0.3.10 depends on azure-iot-device>=2.9.0 and you require toshiba-ac==0.3.10, we can conclude that your requirements are unsatisfiable. hint: Pre-releases are available for `azure-iot-device` in the requested range (e.g., 3.0.0b2), but pre-releases weren't enabled (try: `--prerelease=allow`)

**Comment by acseven** [comment]
> > Hi, I made a temporary fix : [#221](https://github.com/h4de5/home-assistant-toshiba_ac/pull/221)
> > This is not clean at all but it is working. You can just copy the content of my fork into your custom_component folder and restart HA
> 
> It broke again after 2025.3.1 update. Here's the new link for .3.1 from [@albaintor](https://github.com/albaintor) patch:
> 
> https://github.com/h4de5/home-assistant-toshiba_ac/archive/0fc22ed3edacd8cd1cc336cd0d566f6a3adff440.zip

Copied this zip `custom_components/toshiba_ac` folder's content on top of my `toshiba_ac` replacing some files and adding some others, but it still doesn't start after a restart:

`Setup failed for custom integration 'toshiba_ac': Requirements for toshiba_ac not found: ['toshiba-ac==0.3.10']`

**Comment by acseven** [comment]
> > > > Hi, I made a temporary fix : [#221](https://github.com/h4de5/home-assistant-toshiba_ac/pull/221)
> > > > This is not clean at all but it is working. You can just copy the content of my fork into your custom_component folder and restart HA
> > > 
> > > 
> > > It broke again after 2025.3.1 update. Here's the new link for .3.1 from [@albaintor](https://github.com/albaintor) patch:
> > > https://github.com/h4de5/home-assistant-toshiba_ac/archive/0fc22ed3edacd8cd1cc336cd0d566f6a3adff440.zip
> > 
> > 
> > Copied this zip `custom_components/toshiba_ac` folder's content on top of my `toshiba_ac` replacing some files and adding some others, but it still doesn't start after a restart:
> > `Setup failed for custom integration 'toshiba_ac': Requirements for toshiba_ac not found: ['toshiba-ac==0.3.10']`
> > On 2025.3.1
> 
> It works for me. Try removing all files and then unpacking that subdirectory of the zip file.

I've done that a few of times already, and and it still doesn't start, it returns that same error...

**Comment by dkwabek** [comment]
Sam issue here

**Comment by Verturin** [comment]
Same with 2025.3.1

**Comment by acseven** [comment]
> > Hi, I made a temporary fix : [#221](https://github.com/h4de5/home-assistant-toshiba_ac/pull/221)
> > This is not clean at all but it is working. You can just copy the content of my fork into your custom_component folder and restart HA
> 
> It broke again after 2025.3.1 update. Here's the new link for .3.1 from [@albaintor](https://github.com/albaintor) patch:
> 
> https://github.com/h4de5/home-assistant-toshiba_ac/archive/0fc22ed3edacd8cd1cc336cd0d566f6a3adff440.zip

Ok, I figured it out and got it working with your patch file. If you do this right the first time you probably won't get the issue, but if not then you need to edit the `manifest.yaml` file and modify the version number to something else like:

`  "version": "2025.3.1.1",`

Any time you reboot HA with some modification you need to force it reloading by changing the version number.

**Comment by chrisandsally** [comment]
Thanks for the patch, Copied it in and voila.  Awesome.

**Comment by yiggypiggy** [comment]
If the command above doesn't work, try this ssh command:
```shell
cd /config/custom_components
wget https://github.com/h4de5/home-assistant-toshiba_ac/archive/0fc22ed3edacd8cd1cc336cd0d566f6a3adff440.zip
unzip 0fc22ed3edacd8cd1cc336cd0d566f6a3adff440.zip
rm -rf toshiba_ac/
mv home-assistant-toshiba_ac-0fc22ed3edacd8cd1cc336cd0d566f6a3adff440/custom_components/toshiba_ac .
rm -rf home-assistant-toshiba_ac-0fc22ed3edacd8cd1cc336cd0d566f6a3adff440.zip

``` 

Then, modify manifest.json:
```shell
sed -i 's/"version": "[0-9.]*"/"version": "2025.3.1.1"/' toshiba_ac/manifest.json
``` 

Then restart Home Assistant. 

Note: If you don't know how to run an SSH command on HA, you can download the ''Terminal & SSH'' add-on.

**Comment by Mighty-Mike-hub** [comment]
Thanks for the patch - works great
https://github.com/h4de5/home-assistant-toshiba_ac/archive/0fc22ed3edacd8cd1cc336cd0d566f6a3adff440.zip
Toshiba AC is online again

**Comment by gbergadmin** [comment]
Let's hope we'll have a permanet fix for this soon, until the I stay with 2025.2.5

**Comment by silkw0rm** [comment]
> If the command above doesn't work, try this ssh command:
> 
> cd /config/custom_components
> wget https://github.com/h4de5/home-assistant-toshiba_ac/archive/0fc22ed3edacd8cd1cc336cd0d566f6a3adff440.zip
> unzip 0fc22ed3edacd8cd1cc336cd0d566f6a3adff440.zip
> rm -rf toshiba_ac/
> mv home-assistant-toshiba_ac-0fc22ed3edacd8cd1cc336cd0d566f6a3adff440/custom_components/toshiba_ac .
> rm -rf home-assistant-toshiba_ac-0fc22ed3edacd8cd1cc336cd0d566f6a3adff440.zip
> 
> Then, modify manifest.json:
> 
> sed -i 's/"version": "[0-9.]*"/"version": "2025.3.1.1"/' toshiba_ac/manifest.json
> 
> Then restart Home Assistant.
> 
> Note: If you don't know how to run an SSH command on HA, you can download the ''Terminal & SSH'' add-on.

Just wanted to take the time to appreciate & say THANK YOU to everyone involved for resolving this issue and for providing instructions on how to apply the patch. I've followed the instructions given here and the integration is working again.

**Comment by ungrim97** [comment]
Does python not support using different versions in different dependencies.

I am surprised that you cant define that you are dependent on >=2.0.0 of paho-mqtt, and let the azure lib use its own version?

Or is this a limitation of the HA deployment environment

**Comment by Gaafgeel** [comment]
> Patch ok for me.
> 
> Follow this following steps:
> 
> ```
> cd /root/homeassistant/custom_components
> wget https://github.com/h4de5/home-assistant-toshiba_ac/archive/0fc22ed3edacd8cd1cc336cd0d566f6a3adff440.zip
> rm -rf toshiba_ac/
> cp -arv home-assistant-toshiba_ac-0fc22ed3edacd8cd1cc336cd0d566f6a3adff440/custom_components/toshiba_ac .
> ```
> 
> Change `manifest.json` version like `version": "2025.3.1.1`, on `toshiba_ac/manifest.json` file
> 
> Relog you on toshiba and enjoy

Don't forget to unpack the zip before the last step:

`unzip 0fc22ed3edacd8cd1cc336cd0d566f6a3adff440.zip`

**Comment by felixmueller** [comment]
> > Hi [@h4de5](https://github.com/h4de5) ,
> > 
> > Could you please accept the merge request for the workaround developed by [@albaintor](https://github.com/albaintor) ?
> > 
> > It will be useful until a fix in azure
> > 
> > Thanks
> 
> this would copy the whole api into this repository. please understand thats not a
> the way to go from the perspective of the integration. you can use the branch or the provided zip file both should work.

@albaintor: it would be awesome if you could provide some clarification of your changes in https://github.com/KaSroka/Toshiba-AC-control/issues/65, so that @KaSroka can update his library and @h4de5 can update this HA integration to satisfy all the people that are creating new comments every day because they're unable to use this wonderful piece of software 😄
Thank you all so much! 🙏

**Comment by h4de5** [comment]
@albaintor the agreement with microsoft license is still pending: https://github.com/Azure/azure-iot-sdk-python/pull/1205#issuecomment-2703842430

(comment with `@microsoft-github-policy-service agree` there)
not sure if it will help, but maybe.

**Comment by jointlymedia** [comment]
I cannot get the patch working with the SSH commands and changing the version numbers. Any ETA for a update of the service for not so technical people here?

**Comment by KaSroka** [comment]
@jointlymedia for proper fix we need update in a lib provided by Microsoft. Right now they are not willing to update it according to their comment from some time ago. We can make a workaround for this but we need @albaintor input on this or I can create my own fork with changes, I just don't have much time for this. Maybe I can roll something tomorrow.

**Comment by h4de5** [comment]
@KaSroka there is this PR #221 which would copy your whole repo into here - would it be enough to modify your requirements similar to this https://github.com/h4de5/home-assistant-toshiba_ac/pull/221/files#diff-bbef81880c7648e24088b162fa51f1227db32b9e8748eedcd88f18d3cf20ce61 instead?

as you said, MS may take longer to fix this, so moving all over here might not be a temporary solution after all.

**Comment by KaSroka** [comment]
@h4de5 this is my plan for now. But I wanted to understand why @albaintor also downgraded/changed 2 other dependencies of azure-iot-sdk. As he is not responding I will try to figure this out myself

**Comment by KaSroka** [comment]
Should be fixed in #230

**Comment by xvolte** [comment]
Thank you so much for the work :)
Will it be installable through HACS ? I can only see versions of 2024 for now in hacs.
Thanks in advance,

**Comment by h4de5** [comment]
fixed in latest release

**Comment by dkwabek** [comment]
Still get a 500 server error when installing the integration. Anyone an idea what it is

With regards,
D. Kwabek



Op 18 mrt 2025, 10:05, om 10:05, Andi ***@***.***> schreef:

**Comment by ungrim97** [comment]
Likewise still getting issues:

![Image](https://github.com/user-attachments/assets/1007784a-01b1-4c19-a245-bab52be7a6f6)

**Comment by Fudal** [comment]
I have the same problem after updating.

![Image](https://github.com/user-attachments/assets/0150639d-3868-45a5-bae4-d24a08c03c7d)

**Comment by bengohouse** [comment]
Hello,
It works for me with 2025.3.1
Thank you so much

**Comment by Fudal** [comment]
> Hello, It works for me with 2025.3.1 Thank you so much

@bengohouse did you do something else apart of update HA and update toshiba-ac?

**Comment by gavanfantom** [comment]
I had this issue after updating too. I had previously applied the workaround as specified above. I had to remove the toshiba_ac directory and redownload it from HACS to get it working.

It seems that just updating from HACS over the top of the workaround (even redownloading) wasn't enough to update the manifest.json file correctly.

**Comment by acseven** [comment]
I went to HACS and chose re-download the new version, running without any issue. 

Thanks

**Comment by Fudal** [comment]
> I went to HACS and chose re-download the new version, running without any issue.
> 
> Thanks

@acseven thanks, redownload works ;)

**Comment by Benoit34590** [comment]
Hello,
It works for me with 2025.3.1
Thank you

**Comment by Stratovarius666** [comment]
It works for me with HACS.
Thanks!

Il Mar 18 Mar 2025, 14:54 John_Rambo ***@***.***> ha scritto:

**Comment by ungrim97** [comment]
> I went to HACS and chose re-download the new version, running without any issue.
> 
> Thanks

Awesome. Redownloading fixed it

Thanks to everyone involved in getting this back and runing

**Comment by bengohouse** [comment]
@Fudal I just chose to download the latest version (2025.3.1) in HACS.
Dashboard and automations are operational again. Great!!

**Comment by h4de5** [comment]
yep sorry. I made a mistake with 2025.3.5. current version 2025.3.1 should fix it.

thanks to everyone again. specially to @albaintor @KaSroka for preparing and testing!

**Comment by blbeczech82** [comment]
Thank you all and... see you soon here 😄

**Comment by watels** [comment]
Hi,
I did the update to Core 2025.3.4
Operating system 15.1

Still get this error : 
Setup failed for custom integration 'toshiba_ac': Requirements for toshiba_ac not found: ['toshiba-ac==0.3.10'].

Unable to install package toshiba-ac==0.3.10: × No solution found when resolving dependencies: ╰─▶ Because azure-iot-device>=2.9.0,<=2.10.0 depends on paho-mqtt>=1.4.0,<2.0.0 and paho-mqtt==2.1.0, we can conclude that azure-iot-device>=2.9.0,<=2.10.0 cannot be used. And because only the following versions of azure-iot-device are available: azure-iot-device<=2.9.0 azure-iot-device==2.10.0 azure-iot-device==2.11.0 azure-iot-device==2.12.0 azure-iot-device==2.13.0 azure-iot-device==2.13.1 azure-iot-device==2.14.0 we can conclude that azure-iot-device>=2.9.0,<2.11.0 cannot be used. (1) Because azure-iot-device==2.11.0 depends on paho-mqtt>=1.4.0,<2.0.0 and paho-mqtt==2.1.0, we can conclude that azure-iot-device==2.11.0 cannot be used. And because we know from (1) that azure-iot-device>=2.9.0,<2.11.0 cannot be used, we can conclude that azure-iot-device>=2.9.0,<2.12.0 cannot be used. (2) Because azure-iot-device>=2.12.0 depends on paho-mqtt>=1.6.1,<2.0.0 and paho-mqtt==2.1.0, we can conclude that azure-iot-device>=2.12.0 cannot be used. And because we know from (2) that azure-iot-device>=2.9.0,<2.12.0 cannot be used, we can conclude that azure-iot-device>=2.9.0 cannot be used. And because toshiba-ac==0.3.10 depends on azure-iot-device>=2.9.0 and you require toshiba-ac==0.3.10, we can conclude that your requirements are unsatisfiable. hint: Pre-releases are available for `azure-iot-device` in the requested range (e.g., 3.0.0b2), but pre-releases weren't enabled (try: `--prerelease=allow`)

**Comment by KaSroka** [comment]
Seems like you have old version of integration, as latest one uses toshiba-ac version 0.3.11 not 0.3.10

**Comment by watels** [comment]
How can I update toshiba-ac? I have no notification to make an update. I uninstalled and reinstalled module but same version was installed.
